embedding_dim: 128        # 词嵌入维度
hidden_dim: 256          # LSTM 隐藏层维度
output_dim: 8            # 类别数（8个类别）
max_len: 200             # 输入文本的最大长度
batch_size: 8            # 批次大小
epochs: 30               # 训练的轮数
learning_rate: 0.001     # 学习率
dropout_prob: 0.5        # Dropout 概率

fgsm_epsilon: 0.1        # FGSM 扰动强度
pgd_epsilon: 0.1         # PGD 最大扰动范围
pgd_alpha: 0.01          # PGD 每步更新幅度
pgd_iters: 5             # PGD 迭代次数


# 数据路径
train_data: "data/malapi2019/all_analysis_data.txt"
train_labels: "data/malapi2019/labels.txt"

# 模型保存路径
checkpoint_path: 'checkpoints/lstm_adv_pgd.pth' 